### ISSUE TITLE
Please provide StackBlitz

### ISSUE THREAD

**Issue by yatz3000** [volser/cdk-drag-scroll#2]
Hi, @volser!

I'm trying to use the cdk-drag-scroll on my project, and it just isn't working. Could you provide a StackBlitz implementation? That would be really useful.

Thanks!

**Comment by volser** [comment]
https://stackblitz.com/edit/cdk-drag-scroll-demo

**Comment by yatz3000** [comment]
Thanks so much, @volser !

**Comment by yatz3000** [comment]
Hey @volser, I'm trying to get this to work without using the dragDropList, could you take a look at my stackblitz? The dragging item is not staying with the cursor on scroll.
https://stackblitz.com/edit/angular-vfnx1t

**Comment by volser** [comment]
it doesn't support work without using of dragDropList

**Comment by deepak3374** [comment]
is it possible to merge both containers (or pass multiple scroll containers to vsDragScrollContainer as array) ?? In my requirement i have a container for horizontal scroll and other container for vertical scroll
