### ISSUE TITLE
Support for Angular 8

### ISSUE THREAD

**Issue by Jahrenski** [volser/cdk-drag-scroll#4]
Angular 8 being out, would be useful to upgrade the dependencies.

**Comment by volser** [comment]
done

**Comment by Jahrenski** [comment]
Maybe i'm wrong but latest version available is 0.0.6 which does not include angular 8 support.
The current package.json declares a version of 0.0.0 somehow.

npm WARN cdk-drag-scroll@0.0.6 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN cdk-drag-scroll@0.0.6 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN cdk-drag-scroll@0.0.6 requires a peer of @angular/cdk@^7.3.0 but none is installed. You must install peer dependencies yourself.

**Comment by eranshmil** [comment]
> Maybe i'm wrong but latest version available is 0.0.6 which does not include angular 8 support.
> The current package.json declares a version of 0.0.0 somehow.
> 
> npm WARN cdk-drag-scroll@0.0.6 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
> npm WARN cdk-drag-scroll@0.0.6 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.
> npm WARN cdk-drag-scroll@0.0.6 requires a peer of @angular/cdk@^7.3.0 but none is installed. You must install peer dependencies yourself.

Also having this issue.
This happens because of this line: https://github.com/volser/cdk-drag-scroll/blob/master/projects/cdk-drag-scroll/package.json#L8
